BeneficiariesFile now expects a rational number, which can be scaled …
mlabs-haskell/CardStarter-bulk-airdrop-script pull request #20
Opened 2022-02-16 11:46 UTC by jy14898

…by the --decimal-places flag

Fixes https://github.com/mlabs-haskell/CardStarter-bulk-airdrop-script/issues/18.

Should we warn on truncation?

2022-02-17 14:40 UTC, samuelWilliams99 commented
Truncation is an annoying one - i think we need to be REALLY explicit here.
This will extend the task a little bit, but I think the safest bet is to completely fail parsing on truncation - UNLESS, we have a flag that allows it.
This flag should be very explicit that is always rounds down.
So, to summarise:
- Add a truncate flag - make it obvious that it rounds down (using the help text)
- If we try to truncate a value and this flag is not set, fail parsing.

2022-02-17 14:42 UTC, samuelWilliams99 requested changes

2022-02-17 14:42 UTC, samuelWilliams99 commented on src/BeneficiariesFile.hs
> +    scaleAmount r = numerator r * conf.decimalPlaces `div` denominator r
does multiplying the numerator by the decimal places do what we want? should it not be something like `10^decimal places`?

2022-02-18 14:15 UTC, jy14898 commented
I've moved from Rational to Scientific for representing pre-integer token values because:
 - Scientific more naturally represents what we're doing here (c * (10^e))
 - Actually parses correctly

I've added the `--truncate` flag to allow dropping change when rounding down. I've also added a test which checks if the truncation occurs only when it should (regardless of the flag setting).

2022-02-18 14:48 UTC, samuelWilliams99 approved these changes

2022-02-18 14:55 UTC, jy14898 commented on src/BeneficiariesFile.hs
> +    truncated = Just . (*) (10 ^^ b10e) . fromInteger <$> coefficient s `divMod` (10 ^ negate b10e)
I've just pushed another go at it, no longer using point free/tuple functor instance

2022-02-18 14:55 UTC, samuelWilliams99 commented on src/BeneficiariesFile.hs
> +    truncated = Just . (*) (10 ^^ b10e) . fromInteger <$> coefficient s `divMod` (10 ^ negate b10e)
Thats looks better, thanks! Happy to merge when this passes CI

2022-02-18 15:07 UTC, merged